### ISSUE TITLE
Gilbert's review feedback 

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/devfile-stack-starters#4]
All files looks good to me except I have following comments for the pom.xml
- Should use milestone versions?
- Most plugin versions are defined in the `<properties/>` but `maven-compiler-plugin` not, should it be consistent?
  - the guides do not define versions in the `<properties/>`
- based on https://maven.apache.org/plugins/maven-war-plugin/war-mojo.html#failOnMissingWebXml, default is false for 3.1+, may consider to remove `<failOnMissingWebXml>false</failOnMissingWebXml>`
- may consider the test dependecides are need or not
  - `cxf-rt-rs-client`, `cxf-rt-rs-extension-providers`, and `org.glassfish`, specially using MST
- may consider the comment `<!-- Support for JDK 9 and above -->` and the test dependencies under it are necessary or not
  - compiler target and source are set to `11`
  - if using MST, some dependecides may not need

**Comment by scottkurz** [comment]
Thank you @gkwan-ibm, I think we're OK using milestone versions (which adds the copyDependencies support).  I did address most of your comments in #5.
